# 注意开源时这个文件不要提交、或者不要填真实配置
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.33.200.41:3306/pipi
    username: root
    password: root
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0
