spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lulu
    username: root
    password: root
    # session 失效时间
  session:
    cookie:
      domain: localhost
      same-site: none
      secure: true
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  #redis 配置
  redis:
    port: 6379
    host: localhost
    database: 1
    #password: root
    #timeout: 5000        #连接超时时间（毫秒）
server:
  port: 8080
  servlet:
    context-path: /api




mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
